package com.example.crypto.core.ui.util

import com.example.crypto.R

fun getDrawableIdForCoin(symbol: String): Int {
    return when (symbol.lowercase()) {
        "btc" -> R.drawable.btc
        "eth" -> R.drawable.eth
        "wbtc" -> R.drawable.wbtc
        "usdt" -> R.drawable.usdt
        "bnb" -> R.drawable.bnb
        "ada" -> R.drawable.ada
        "xrp" -> R.drawable.xrp
        "doge" -> R.drawable.doge
        "sol" -> R.drawable.sol
        "dot" -> R.drawable.dot
        "shib" -> R.drawable.shib
        "ltc" -> R.drawable.ltc
        "trx" -> R.drawable.trx
        "matic" -> R.drawable.matic
        "link" -> R.drawable.link
        "usdc" -> R.drawable.usdc
        "avax" -> R.drawable.avax
        "ftt" -> R.drawable.ftt
        "uni" -> R.drawable.uni
        "bch" -> R.drawable.bch
        "atom" -> R.drawable.atom
        "luna" -> R.drawable.luna
        "near" -> R.drawable.near
        "dai" -> R.drawable.dai
        "xlm" -> R.drawable.xlm
        "mana" -> R.drawable.mana
        "vet" -> R.drawable.vet
        "icp" -> R.drawable.icp
        "sand" -> R.drawable.sand
        "ftm" -> R.drawable.ftm
        "axs" -> R.drawable.axs
        "xtz" -> R.drawable.xtz
        "egld" -> R.drawable.egld
        "hbar" -> R.drawable.hbar
        "theta" -> R.drawable.theta
        "aave" -> R.drawable.aave
        "eos" -> R.drawable.eos
        "cake" -> R.drawable.cake
        "miota" -> R.drawable.miota
        "grt" -> R.drawable.grt
        "xmr" -> R.drawable.xmr
        "klay" -> R.drawable.klay
        "one" -> R.drawable.one
        "hnt" -> R.drawable.hnt
        "leo" -> R.drawable.leo
        "flow" -> R.drawable.flow
        "bsv" -> R.drawable.bsv
        "etc" -> R.drawable.etc
        "gala" -> R.drawable.gala
        "kcs" -> R.drawable.kcs
        "mkr" -> R.drawable.mkr
        "zec" -> R.drawable.zec
        "enj" -> R.drawable.enj
        "neo" -> R.drawable.neo
        "stx" -> R.drawable.stx
        "qnt" -> R.drawable.qnt
        "chz" -> R.drawable.chz
        "celo" -> R.drawable.celo
        "hot" -> R.drawable.hot
        "mina" -> R.drawable.mina
        "xmy" -> R.drawable.xmy
        "cxo" -> R.drawable.cxo
        "abt" -> R.drawable.abt
        "ptoy" -> R.drawable.ptoy
        "hydro" -> R.drawable.hydro
        "vtc" -> R.drawable.vtc
        "tch" -> R.drawable.tch
        "xvs" -> R.drawable.xvs
        "cce" -> R.drawable.cce
        "tribe" -> R.drawable.tribe
        "like" -> R.drawable.like
        "rcn" -> R.drawable.rcn
        "2key" -> R.drawable._2key
        "vsys" -> R.drawable.vsys
        "pnk" -> R.drawable.pnk
        "plt" -> R.drawable.plt
        "yfi" -> R.drawable.yfi
        "plc" -> R.drawable.plc
        "lrc" -> R.drawable.lrc
        "ersdl" -> R.drawable.ersdl
        "plu" -> R.drawable.plu
        "icx" -> R.drawable.icx
        "rvn" -> R.drawable.rvn
        "wicc" -> R.drawable.wicc
        "ldo" -> R.drawable.ldo
        "cloak" -> R.drawable.cloak
        "oxt" -> R.drawable.oxt
        "dia" -> R.drawable.dia
        "xmx" -> R.drawable.xmx
        "xnc" -> R.drawable.xnc
        "hex" -> R.drawable.hex
        "face" -> R.drawable.face
        "mxc" -> R.drawable.mxc
        "ant" -> R.drawable.ant
        "anc" -> R.drawable.anc
        "payx" -> R.drawable.payx
        "meta" -> R.drawable.meta
        "xor" -> R.drawable.xor
        "cmm" -> R.drawable.cmm
        "myst" -> R.drawable.myst
        "shroom" -> R.drawable.shroom
        "xwc" -> R.drawable.xwc
        "revv" -> R.drawable.revv
        "xvg" -> R.drawable.xvg
        "dent" -> R.drawable.dent
        "tbx" -> R.drawable.tbx
        "gvt" -> R.drawable.gvt
        "orbs" -> R.drawable.orbs
        "eng" -> R.drawable.eng
        "kmd" -> R.drawable.kmd
        "suter" -> R.drawable.suter
        "swth" -> R.drawable.swth
        "ngc" -> R.drawable.ngc
        "snow" -> R.drawable.snow
        "glm" -> R.drawable.glm
        "eum" -> R.drawable.eum
        "safemoon" -> R.drawable.safemoon
        "inj" -> R.drawable.inj
        "ouro" -> R.drawable.ouro
        "pcx" -> R.drawable.pcx
        "ion" -> R.drawable.ion
        "nftx" -> R.drawable.nftx
        "ink" -> R.drawable.ink
        "1inch" -> R.drawable._1inch
        "smart" -> R.drawable.smart
        "klv" -> R.drawable.klv
        "eca" -> R.drawable.eca
        "wing" -> R.drawable.wing
        "rlc" -> R.drawable.rlc
        "seele" -> R.drawable.seele
        "shift" -> R.drawable.shift
        "tau" -> R.drawable.tau
        "mbl" -> R.drawable.mbl
        "divi" -> R.drawable.divi
        "fsn" -> R.drawable.fsn
        "jst" -> R.drawable.jst
        "strk" -> R.drawable.strk
        "fet" -> R.drawable.fet
        "gt" -> R.drawable.gt
        "ruff" -> R.drawable.ruff
        "xcp" -> R.drawable.xcp
        "xbc" -> R.drawable.xbc
        "ttt" -> R.drawable.ttt
        "tvk" -> R.drawable.tvk
        "waxp" -> R.drawable.waxp
        "burst" -> R.drawable.burst
        "nuls" -> R.drawable.nuls
        "bcha" -> R.drawable.bcha
        "cnd" -> R.drawable.cnd
        "pols" -> R.drawable.pols
        "xym" -> R.drawable.xym
        "qsp" -> R.drawable.qsp
        "pundix" -> R.drawable.pundix
        "dfi" -> R.drawable.dfi
        "nrg" -> R.drawable.nrg
        "aeon" -> R.drawable.aeon
        "mona" -> R.drawable.mona
        "pma" -> R.drawable.pma
        "plr" -> R.drawable.plr
        "ust" -> R.drawable.ust
        "ino" -> R.drawable.ino
        "nim" -> R.drawable.nim
        "cspr" -> R.drawable.cspr
        "dock" -> R.drawable.dock
        "pac" -> R.drawable.pac
        "win" -> R.drawable.win
        "nft" -> R.drawable.nft
        "etz" -> R.drawable.etz
        "pyr" -> R.drawable.pyr
        "pink" -> R.drawable.pink
        "wings" -> R.drawable.wings
        "kat" -> R.drawable.kat
        "xprt" -> R.drawable.xprt
        "mith" -> R.drawable.mith
        "sc" -> R.drawable.sc
        "ava" -> R.drawable.ava
        "veri" -> R.drawable.veri
        "mvl" -> R.drawable.mvl
        "scrt" -> R.drawable.scrt
        "ctk" -> R.drawable.ctk
        "cvt" -> R.drawable.cvt
        "polis" -> R.drawable.polis
        "cvc" -> R.drawable.cvc
        "esbc" -> R.drawable.esbc
        "aoa" -> R.drawable.aoa
        "bora" -> R.drawable.bora
        "alpha" -> R.drawable.alpha
        "iris" -> R.drawable.iris
        "mco" -> R.drawable.mco
        "sfp" -> R.drawable.sfp
        "coti" -> R.drawable.coti
        "fuel" -> R.drawable.fuel
        "algo" -> R.drawable.algo
        "lido" -> R.drawable.lido
        "pivx" -> R.drawable.pivx
        "colx" -> R.drawable.colx
        "ewt" -> R.drawable.ewt
        "husd" -> R.drawable.husd
        "prom" -> R.drawable.prom
        "tern" -> R.drawable.tern
        "gal" -> R.drawable.gal
        "lrg" -> R.drawable.lrg
        "etn" -> R.drawable.etn
        "vtho" -> R.drawable.vtho
        "itc" -> R.drawable.itc
        "renbtc" -> R.drawable.renbtc
        "sumo" -> R.drawable.sumo
        "kok" -> R.drawable.kok
        "celr" -> R.drawable.celr
        "vbnb" -> R.drawable.vbnb
        "xyo" -> R.drawable.xyo
        "bzrx" -> R.drawable.bzrx
        "cob" -> R.drawable.cob
        "omg" -> R.drawable.omg
        "act" -> R.drawable.act
        "vrsc" -> R.drawable.vrsc
        "exrd" -> R.drawable.exrd
        "qkc" -> R.drawable.qkc
        "flm" -> R.drawable.flm
        "xdb" -> R.drawable.xdb
        "cro" -> R.drawable.cro
        "trb" -> R.drawable.trb
        "sxp" -> R.drawable.sxp
        "xhv" -> R.drawable.xhv
        "mph" -> R.drawable.mph
        "salt" -> R.drawable.salt
        "nexo" -> R.drawable.nexo
        "tt" -> R.drawable.tt
        "stak" -> R.drawable.stak
        "maapl" -> R.drawable.maapl
        "prq" -> R.drawable.prq
        "nye" -> R.drawable.nye
        "perl" -> R.drawable.perl
        "bto" -> R.drawable.bto
        "btx" -> R.drawable.btx
        "beam" -> R.drawable.beam
        "wnxm" -> R.drawable.wnxm
        "iotx" -> R.drawable.iotx
        "akro" -> R.drawable.akro
        "rsv" -> R.drawable.rsv
        "hakka" -> R.drawable.hakka
        "uma" -> R.drawable.uma
        "bos" -> R.drawable.bos
        "key" -> R.drawable.key
        "htr" -> R.drawable.htr
        "clam" -> R.drawable.clam
        "orc" -> R.drawable.orc
        "vra" -> R.drawable.vra
        "fun" -> R.drawable.fun_
        "emc2" -> R.drawable.emc2
        "msr" -> R.drawable.msr
        "fct" -> R.drawable.fct
        "dth" -> R.drawable.dth
        "ship" -> R.drawable.ship
        "xdc" -> R.drawable.xdc
        "btcz" -> R.drawable.btcz
        "solo" -> R.drawable.solo
        "qlc" -> R.drawable.qlc
        "atri" -> R.drawable.atri
        "vrt" -> R.drawable.vrt
        "dego" -> R.drawable.dego
        "vrc" -> R.drawable.vrc
        "karma" -> R.drawable.karma
        "wtc" -> R.drawable.wtc
        "pre" -> R.drawable.pre
        "ren" -> R.drawable.ren
        "edg" -> R.drawable.edg
        "game" -> R.drawable.game
        "rose" -> R.drawable.rose
        "idex" -> R.drawable.idex
        "meetone" -> R.drawable.meetone
        "nmc" -> R.drawable.nmc
        "nlg" -> R.drawable.nlg
        "tusd" -> R.drawable.tusd
        "ctsi" -> R.drawable.ctsi
        "nav" -> R.drawable.nav
        "btm" -> R.drawable.btm
        "kin" -> R.drawable.kin
        "dvpn" -> R.drawable.dvpn
        "lusd" -> R.drawable.lusd
        "bcd" -> R.drawable.bcd
        "bal" -> R.drawable.bal
        "bmx" -> R.drawable.bmx
        "nxt" -> R.drawable.nxt
        "bnt" -> R.drawable.bnt
        "xpr" -> R.drawable.xpr
        "band" -> R.drawable.band
        "mdx" -> R.drawable.mdx
        "soul" -> R.drawable.soul
        "axel" -> R.drawable.axel
        "hoge" -> R.drawable.hoge
        "okb" -> R.drawable.okb
        "crpt" -> R.drawable.crpt
        "zrx" -> R.drawable.zrx
        "sub" -> R.drawable.sub
        "stq" -> R.drawable.stq
        "ok" -> R.drawable.ok
        "reef" -> R.drawable.reef
        "forth" -> R.drawable.forth
        "mft" -> R.drawable.mft
        "ark" -> R.drawable.ark
        "sls" -> R.drawable.sls
        "btcst" -> R.drawable.btcst
        "xpa" -> R.drawable.xpa
        "pltc" -> R.drawable.pltc
        "iqn" -> R.drawable.iqn
        "agix" -> R.drawable.agix
        "qtum" -> R.drawable.qtum
        "ern" -> R.drawable.ern
        "nas" -> R.drawable.nas
        "agrs" -> R.drawable.agrs
        "rdn" -> R.drawable.rdn
        "busd" -> R.drawable.busd
        "cennz" -> R.drawable.cennz
        "ult" -> R.drawable.ult
        "hedg" -> R.drawable.hedg
        "tel" -> R.drawable.tel
        "stmx" -> R.drawable.stmx
        "dao" -> R.drawable.dao
        "dbc" -> R.drawable.dbc
        "slr" -> R.drawable.slr
        "snm" -> R.drawable.snm
        "tix" -> R.drawable.tix
        "cube" -> R.drawable.cube
        "ar" -> R.drawable.ar
        "sys" -> R.drawable.sys
        "ae" -> R.drawable.ae
        "alice" -> R.drawable.alice
        "rise" -> R.drawable.rise
        "oxen" -> R.drawable.oxen
        "loom" -> R.drawable.loom
        "snx" -> R.drawable.snx
        "slp" -> R.drawable.slp
        "vite" -> R.drawable.vite
        "cfx" -> R.drawable.cfx
        "dcr" -> R.drawable.dcr
        "ten" -> R.drawable.ten
        "cet" -> R.drawable.cet
        "dash" -> R.drawable.dash
        "mass" -> R.drawable.mass
        "appc" -> R.drawable.appc
        "kndc" -> R.drawable.kndc
        "rsr" -> R.drawable.rsr
        "woo" -> R.drawable.woo
        "ksp" -> R.drawable.ksp
        "arpa" -> R.drawable.arpa
        "nmr" -> R.drawable.nmr
        "auto" -> R.drawable.auto
        "rari" -> R.drawable.rari
        "dodo" -> R.drawable.dodo
        "krb" -> R.drawable.krb
        "ebst" -> R.drawable.ebst
        "rfr" -> R.drawable.rfr
        "lon" -> R.drawable.lon
        "ardr" -> R.drawable.ardr
        "blz" -> R.drawable.blz
        "chr" -> R.drawable.chr
        "tks" -> R.drawable.tks
        "dnt" -> R.drawable.dnt
        "hxro" -> R.drawable.hxro
        "om" -> R.drawable.om
        "la" -> R.drawable.la
        "btcp" -> R.drawable.btcp
        "rune" -> R.drawable.rune
        "thr" -> R.drawable.thr
        "apl" -> R.drawable.apl
        "snt" -> R.drawable.snt
        "mds" -> R.drawable.mds
        "pro" -> R.drawable.pro
        "ppp" -> R.drawable.ppp
        "abbc" -> R.drawable.abbc
        "nano" -> R.drawable.nano
        "ubq" -> R.drawable.ubq
        "zeon" -> R.drawable.zeon
        "burger" -> R.drawable.burger
        "pbtc" -> R.drawable.pbtc
        "utk" -> R.drawable.utk
        "cusdc" -> R.drawable.cusdc
        "cusdt" -> R.drawable.cusdt
        "pha" -> R.drawable.pha
        "esd" -> R.drawable.esd
        "arrr" -> R.drawable.arrr
        "trtl" -> R.drawable.trtl
        "belt" -> R.drawable.belt
        "fida" -> R.drawable.fida
        "wgro" -> R.drawable.wgro
        "hbtc" -> R.drawable.hbtc
        "nct" -> R.drawable.nct
        "tpay" -> R.drawable.tpay
        "btg" -> R.drawable.btg
        "bcn" -> R.drawable.bcn
        "grc" -> R.drawable.grc
        "rif" -> R.drawable.rif
        "ekt" -> R.drawable.ekt
        "ftc" -> R.drawable.ftc
        "zel" -> R.drawable.zel
        "dmt" -> R.drawable.dmt
        "bf" -> R.drawable.bf
        "vibe" -> R.drawable.vibe
        "botx" -> R.drawable.botx
        "start" -> R.drawable.start
        "dvi" -> R.drawable.dvi
        "ode" -> R.drawable.ode
        "cre" -> R.drawable.cre
        "spank" -> R.drawable.spank
        "shft" -> R.drawable.shft
        "btmx" -> R.drawable.btmx
        "basic" -> R.drawable.basic
        "ast" -> R.drawable.ast
        "met" -> R.drawable.met
        "zen" -> R.drawable.zen
        "cel" -> R.drawable.cel
        "zb" -> R.drawable.zb
        "xpm" -> R.drawable.xpm
        "bnk" -> R.drawable.bnk
        "firo" -> R.drawable.firo
        "eurs" -> R.drawable.eurs
        "rep" -> R.drawable.rep
        "mask" -> R.drawable.mask
        "auction" -> R.drawable.auction
        "lym" -> R.drawable.lym
        "ghst" -> R.drawable.ghst
        "susd" -> R.drawable.susd
        "lun" -> R.drawable.lun
        "chat" -> R.drawable.chat
        "steem" -> R.drawable.steem
        "plbt" -> R.drawable.plbt
        "bela" -> R.drawable.bela
        "maid" -> R.drawable.maid
        "bts" -> R.drawable.bts
        "req" -> R.drawable.req
        "bar" -> R.drawable.bar
        "perp" -> R.drawable.perp
        "egt" -> R.drawable.egt
        "lina" -> R.drawable.lina
        "gusd" -> R.drawable.gusd
        "zil" -> R.drawable.zil
        "zks" -> R.drawable.zks
        "dat" -> R.drawable.dat
        "san" -> R.drawable.san
        "xin" -> R.drawable.xin
        "adk" -> R.drawable.adk
        "part" -> R.drawable.part
        "xem" -> R.drawable.xem
        "via" -> R.drawable.via
        "crd" -> R.drawable.crd
        "crw" -> R.drawable.crw
        "nu" -> R.drawable.nu
        "ocean" -> R.drawable.ocean
        "cream" -> R.drawable.cream
        "pasc" -> R.drawable.pasc
        "adx" -> R.drawable.adx
        "ckb" -> R.drawable.ckb
        "tko" -> R.drawable.tko
        "mir" -> R.drawable.mir
        "dag" -> R.drawable.dag
        "grs" -> R.drawable.grs
        "gin" -> R.drawable.gin
        "lto" -> R.drawable.lto
        "ksm" -> R.drawable.ksm
        "wan" -> R.drawable.wan
        "wbnb" -> R.drawable.wbnb
        "titan" -> R.drawable.titan
        "erg" -> R.drawable.erg
        "rfox" -> R.drawable.rfox
        "lbc" -> R.drawable.lbc
        "bmc" -> R.drawable.bmc
        "dcn" -> R.drawable.dcn
        "xsr" -> R.drawable.xsr
        "tkn" -> R.drawable.tkn
        "cs" -> R.drawable.cs
        "storj" -> R.drawable.storj
        "vgx" -> R.drawable.vgx
        "hns" -> R.drawable.hns
        "crv" -> R.drawable.crv
        "tomo" -> R.drawable.tomo
        "mx" -> R.drawable.mx
        "ampl" -> R.drawable.ampl
        "hai" -> R.drawable.hai
        "xdn" -> R.drawable.xdn
        "akt" -> R.drawable.akt
        "btcb" -> R.drawable.btcb
        "ignis" -> R.drawable.ignis
        "vee" -> R.drawable.vee
        "qun" -> R.drawable.qun
        "mda" -> R.drawable.mda
        "stake" -> R.drawable.stake
        "dlt" -> R.drawable.dlt
        "rbtc" -> R.drawable.rbtc
        "fxs" -> R.drawable.fxs
        "nxm" -> R.drawable.nxm
        "gsc" -> R.drawable.gsc
        "uos" -> R.drawable.uos
        "cdai" -> R.drawable.cdai
        "rev" -> R.drawable.rev
        "ubt" -> R.drawable.ubt
        "yoyow" -> R.drawable.yoyow
        "btt" -> R.drawable.btt
        "ihf" -> R.drawable.ihf
        "btu" -> R.drawable.btu
        "pirl" -> R.drawable.pirl
        "nwc" -> R.drawable.nwc
        "bat" -> R.drawable.bat
        "egr" -> R.drawable.egr
        "rdd" -> R.drawable.rdd
        "ppt" -> R.drawable.ppt
        "sushi" -> R.drawable.sushi
        "ppc" -> R.drawable.ppc
        "hum" -> R.drawable.hum
        "sbd" -> R.drawable.sbd
        "med" -> R.drawable.med
        "soc" -> R.drawable.soc
        "bond" -> R.drawable.bond
        "kava" -> R.drawable.kava
        "asta" -> R.drawable.asta
        "cru" -> R.drawable.cru
        "nebl" -> R.drawable.nebl
        "ogn" -> R.drawable.ogn
        "srn" -> R.drawable.srn
        "drc" -> R.drawable.drc
        "xas" -> R.drawable.xas
        "tzc" -> R.drawable.tzc
        "wozx" -> R.drawable.wozx
        "skl" -> R.drawable.skl
        "omni" -> R.drawable.omni
        "qrl" -> R.drawable.qrl
        "audio" -> R.drawable.audio
        "dgb" -> R.drawable.dgb
        "mns" -> R.drawable.mns
        "sapp" -> R.drawable.sapp
        "bix" -> R.drawable.bix
        "asafe" -> R.drawable.asafe
        "pearl" -> R.drawable.pearl
        "gno" -> R.drawable.gno
        "comp" -> R.drawable.comp
        "hush" -> R.drawable.hush
        "waves" -> R.drawable.waves
        "lpt" -> R.drawable.lpt
        "new" -> R.drawable.new_
        "pnt" -> R.drawable.pnt
        "ella" -> R.drawable.ella
        "ray" -> R.drawable.ray
        "gxc" -> R.drawable.gxc
        "best" -> R.drawable.best
        "dawn" -> R.drawable.dawn
        "knc" -> R.drawable.knc
        "frax" -> R.drawable.frax
        "hpp" -> R.drawable.hpp
        "ddx" -> R.drawable.ddx
        "zlw" -> R.drawable.zlw
        "nest" -> R.drawable.nest
        "veil" -> R.drawable.veil
        "oot" -> R.drawable.oot
        "fei" -> R.drawable.fei
        "ong" -> R.drawable.ong
        "xcm" -> R.drawable.xcm
        "sngls" -> R.drawable.sngls
        "srm" -> R.drawable.srm
        "vlx" -> R.drawable.vlx
        "grin" -> R.drawable.grin
        "dusk" -> R.drawable.dusk
        "fx" -> R.drawable.fx
        "tlm" -> R.drawable.tlm
        "aergo" -> R.drawable.aergo
        "sphtx" -> R.drawable.sphtx
        "tfuel" -> R.drawable.tfuel
        "elf" -> R.drawable.elf
        "lkk" -> R.drawable.lkk
        "iost" -> R.drawable.iost
        "gls" -> R.drawable.gls
        "neu" -> R.drawable.neu
        "poe" -> R.drawable.poe
        "bnty" -> R.drawable.bnty
        "aeth" -> R.drawable.aeth
        "pay" -> R.drawable.pay
        "tera" -> R.drawable.tera
        "gbx" -> R.drawable.gbx
        "iop" -> R.drawable.iop
        "super" -> R.drawable._super
        "bnana" -> R.drawable.bnana
        "moac" -> R.drawable.moac
        "pax" -> R.drawable.pax
        "inb" -> R.drawable.inb
        "aion" -> R.drawable.aion
        "bst" -> R.drawable.bst
        "data" -> R.drawable.data
        "ramp" -> R.drawable.ramp
        "gtc" -> R.drawable.gtc
        "emc" -> R.drawable.emc
        "mln" -> R.drawable.mln
        "html" -> R.drawable.html
        "xuc" -> R.drawable.xuc
        "zcl" -> R.drawable.zcl
        "sky" -> R.drawable.sky
        "mth" -> R.drawable.mth
        "lqty" -> R.drawable.lqty
        "nlc2" -> R.drawable.nlc2
        "vai" -> R.drawable.vai
        "amp" -> R.drawable.amp
        "alt" -> R.drawable.alt
        "ctc" -> R.drawable.ctc
        "paxg" -> R.drawable.paxg
        "youc" -> R.drawable.youc
        "oax" -> R.drawable.oax
        "xby" -> R.drawable.xby
        "mtl" -> R.drawable.mtl
        "ceth" -> R.drawable.ceth
        "sib" -> R.drawable.sib
        "qqq" -> R.drawable.qqq
        "dgd" -> R.drawable.dgd
        "mof" -> R.drawable.mof
        "rly" -> R.drawable.rly
        "noia" -> R.drawable.noia
        "qash" -> R.drawable.qash
        "ryo" -> R.drawable.ryo
        "strax" -> R.drawable.strax
        "exp" -> R.drawable.exp
        "uqc" -> R.drawable.uqc
        "ankr" -> R.drawable.ankr
        "bifi" -> R.drawable.bifi
        "ncash" -> R.drawable.ncash
        "arnx" -> R.drawable.arnx
        "math" -> R.drawable.math
        "hive" -> R.drawable.hive
        "wpr" -> R.drawable.wpr
        "strong" -> R.drawable.strong
        "mlk" -> R.drawable.mlk
        "znn" -> R.drawable.znn
        "pond" -> R.drawable.pond
        "tor" -> R.drawable.tor
        "torn" -> R.drawable.torn
        "fil" -> R.drawable.fil
        "drs" -> R.drawable.drs
        "twt" -> R.drawable.twt
        "iq" -> R.drawable.iq
        "cusd" -> R.drawable.cusd
        "ont" -> R.drawable.ont
        "block" -> R.drawable.block
        "mwc" -> R.drawable.mwc
        "tnc" -> R.drawable.tnc
        "oxy" -> R.drawable.oxy
        "tnt" -> R.drawable.tnt
        "shr" -> R.drawable.shr
        "poly" -> R.drawable.poly
        "bake" -> R.drawable.bake
        "wrx" -> R.drawable.wrx
        "tlos" -> R.drawable.tlos
        "chsb" -> R.drawable.chsb
        "ctxc" -> R.drawable.ctxc
        "bsd" -> R.drawable.bsd
        "pot" -> R.drawable.pot
        "lsk" -> R.drawable.lsk
        "gas" -> R.drawable.gas
        "nkn" -> R.drawable.nkn
        "etp" -> R.drawable.etp
        "usdn" -> R.drawable.usdn
        "evx" -> R.drawable.evx
        "swap" -> R.drawable.swap
        "keep" -> R.drawable.keep
        "ccxx" -> R.drawable.ccxx
        "ela" -> R.drawable.ela
        "kai" -> R.drawable.kai
        "cmt" -> R.drawable.cmt
        "tnb" -> R.drawable.tnb
        "ht" -> R.drawable.ht
        "fio" -> R.drawable.fio
        "hc" -> R.drawable.hc
        "powr" -> R.drawable.powr
        "fjc" -> R.drawable.fjc
        "drg" -> R.drawable.drg
        else -> R.drawable.ic_launcher_foreground
    }
}